// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYA8gMZrt0Wn9F0Jer2Az_nFfvjQuWrBA',
    appId: '1:802081621991:web:061db5da9694bd9a649f42',
    messagingSenderId: '802081621991',
    projectId: 'heaven-hunt-63924',
    authDomain: 'heaven-hunt-63924.firebaseapp.com',
    storageBucket: 'heaven-hunt-63924.appspot.com',
    measurementId: 'G-CNZGSZS39L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrJ5MGcorfyz-8TTUvFDuq6P0P9f1ulLI',
    appId: '1:802081621991:android:98ac19f1a4a5018c649f42',
    messagingSenderId: '802081621991',
    projectId: 'heaven-hunt-63924',
    storageBucket: 'heaven-hunt-63924.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfKpKYuq5POxpUi5cpg_GKx_pKAkIhnSg',
    appId: '1:802081621991:ios:b4bf623dd7d3c0f6649f42',
    messagingSenderId: '802081621991',
    projectId: 'heaven-hunt-63924',
    storageBucket: 'heaven-hunt-63924.appspot.com',
    iosClientId: '802081621991-vpo7uelqb91r7vo504fu5sdmpmh018j7.apps.googleusercontent.com',
    iosBundleId: 'com.meesalapavan.heavenhunt',
  );
}
